name: 'Trigger CircleCI Pipeline'
description: 'Trigger pipelines on CircleCI for any event on GitHub.'
branding:
    icon: "check-circle"
    color: "green"
inputs:
  GHA_Meta:
    required: false
    description: 'An optional additional metadata parameter. Will be available on the CircleCI pipeline as GHA_Meta'
  GHA_SHA:
    required: false
    description: 'An optional additional metadata parameter. Will be used as the tag'
runs:
  using: 'node12'
  main: 'dist/index.js'
